export const SEARCH_TEXT = "Search superheros here";
export const APP_TITLE_P1 = "Super.";
export const APP_TITLE_P2 = "Heros.";
export const NAV_LINK_SUPERHERO = "SuperHeros";
export const NAV_LINK_ABOUT = "About";
export const NAV_LINK_FAVOURITES = "Favourites"
export const NAV_ITEM_SUPERHERO = "superhero_nav";
export const NAV_ITEM_ABOUT = "about_nav";
export const NAV_ITEM_FAVOURITE = "fav_nav";
export const POWERSTATS = "POWERSTATS";
export const BIOGRAPHY = "BIOGRAPHY";
export const APPEARANCE = "APPEARANCE";
export const CONNECTIONS = "CONNECTIONS";